export const contacts = [
  {
    id: crypto.randomUUID(),
    firstName: "نوید",
    lastName: "علی اکبری",
    relative: "دوست",
    phoneNumber: "09135948292",
    email: "navidaliakbari.206@gmail.com",
  },
  {
    id: crypto.randomUUID(),
    firstName: "یونس",
    lastName: "علی خاصی",
    relative: "دوست",
    phoneNumber: "09135948292",
    email: "younes.206@gmail.com",
  },
  {
    id: crypto.randomUUID(),
    firstName: "نیما",
    lastName: "عالمیان",
    relative: "همکار",
    phoneNumber: "09135948292",
    email: "nimalamian@yahoo.com",
  },
  {
    id: crypto.randomUUID(),
    firstName: "میثم",
    lastName: "فرزعلیان",
    relative: "دوست",
    phoneNumber: "09121212365",
    email: "meysamfarzalian@yahoo.com",
  },
  {
    id: crypto.randomUUID(),
    firstName: "محمد عرفان",
    lastName: "مزید آبادی فراهانی",
    relative: "دوست",
    phoneNumber: "09124588855",
    email: "erfanmazidabadi@gmail.com",
  },
  {
    id: crypto.randomUUID(),
    firstName: "علیرضا",
    lastName: "قرقابی",
    relative: "دوست",
    phoneNumber: "09152547859",
    email: "alirezagharghabi@yahoo.com",
  },
  {
    id: crypto.randomUUID(),
    firstName: "علی",
    lastName: "کوشش",
    relative: "دوست",
    phoneNumber: "09152547859",
    email: "alikoshesh@yahoo.com",
  },
  {
    id: crypto.randomUUID(),
    firstName: "سعید",
    lastName: "لک",
    relative: "دوست",
    phoneNumber: "09152547859",
    email: "saeidlak@gmail.com",
  },
  {
    id: crypto.randomUUID(),
    firstName: "پوریا",
    lastName: "عصرزاد",
    relative: "دوست",
    phoneNumber: "09152547859",
    email: "asrzadpouria@yahoo.com",
  },
  {
    id: crypto.randomUUID(),
    firstName: "سروش",
    lastName: "علیزاده",
    relative: "همکار",
    phoneNumber: "09121212365",
    email: "soroushalizadeh@yahoo.com",
  },
  {
    id: crypto.randomUUID(),
    firstName: "امیرعلی",
    lastName: "اقدامی",
    relative: "دوست",
    phoneNumber: "09124588855",
    email: "amiralieghdami.12@yahoo.com",
  },
  {
    id: crypto.randomUUID(),
    firstName: "امین",
    lastName: "احسانیان",
    relative: "دوست",
    phoneNumber: "09152547859",
    email: "aminehsanian@yahoo.com",
  },
];
